language: android
jdk: oraclejdk8
sudo: true

branches:
  only:
    - "master"

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - android-24

    # emulators
    - sys-img-armeabi-v7a-addon-google_apis-google-24

before_script:
  - echo no | android create avd --force -n test -t android-27 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew clean
  - ./gradlew testDebugUnitTest connectedDebugAndroidTest
