language: android
jdk: oraclejdk8
sudo: true

branches:
  only:
    - "master"

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

    # emulators
    - sys-img-armeabi-v7a-android-27

#before_script:
#  - echo no | android create avd --force -n test -t android-27 --abi armeabi-v7a
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

script: ./gradlew clean
script: ./gradlew testDebugUnitTest connectedDebugAndroidTest
